name: al_quran_v3
description: "A Flutter application for reading the Holy Quran with Recitation"

version: 2.0.0+16

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.0
  gap: ^3.0.1
  fluentui_system_icons: ^1.1.273
  html: ^0.15.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  bloc: ^9.0.0
  permission_handler: ^12.0.0+1
  flutter_svg: ^2.0.17
  just_audio: ^0.10.3
  just_audio_media_kit: ^2.1.0
  just_audio_background: ^0.0.1-beta.17
  audio_video_progress_bar: ^2.0.3
  dartx: ^1.2.0
  fluttertoast: ^8.2.12
  url_launcher: ^6.3.1
  path_provider: ^2.1.5
  cached_network_image: ^3.4.1
  device_info_plus: ^11.4.0
  package_info_plus: ^8.3.0
  path: ^1.9.1
  share_plus: ^11.0.0
  simple_icons: ^14.6.1
  shared_preferences: ^2.5.3
  flutter_localizations: 
    sdk: flutter             

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3
  icons_launcher: ^3.0.1


flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/img/
    - assets/
    - assets/quran_script/
    - assets/meta_data/


  fonts:
    - family: QPC_Hafs 
      fonts:
        - asset: assets/fonts/Quran/QPC Hafs font.ttf

    - family: NotoSans
      fonts:
        - asset: assets/fonts/App/NotoSans-Bold.ttf
          weight: 700 
        - asset: assets/fonts/App/NotoSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/App/NotoSans-Light.ttf
          weight: 300
        - asset: assets/fonts/App/NotoSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/App/NotoSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/App/NotoSans-SemiBold.ttf
          weight: 600

icons_launcher:
  image_path: "assets/img/logo.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true
  
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/img/logo.png"
  min_sdk_android: 21 
