name: al_quran_v3
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.0
  shared_preferences: ^2.5.3
  google_fonts: ^6.2.1
  gap: ^3.0.1
  fluentui_system_icons: ^1.1.273
  intl: ^0.20.2
  html: ^0.15.5
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/img/
    - assets/
    - assets/dev/
    - assets/quran_script/
    - assets/meta_data/

  fonts:
    - family: QPC_Hafs 
      fonts:
        - asset: assets/fonts/Quran/QPC Hafs font.ttf

    - family: IndopakNastaleeq
      fonts:
        - asset: assets/fonts/Quran/Indopak Nastaleeq font.ttf

    - family: SurahNames
      fonts:
        - asset: assets/fonts/Quran/V4 Surah Name Font.ttf
