name: al_quran_v3
description: "A new Flutter project."

version: 3.0.0-dev-2+3

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.0
  shared_preferences: ^2.5.3
  gap: ^3.0.1
  fluentui_system_icons: ^1.1.273
  intl: ^0.20.2
  html: ^0.15.5
  toastification: ^3.0.2
  http: ^1.3.0
  archive: ^4.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  meta: ^1.16.0
  bloc: ^9.0.0
  dio: ^5.8.0+1
  scrollable_positioned_list: ^0.3.8
  flutter_compass: ^0.8.1
  permission_handler: ^12.0.0+1
  geolocator: ^14.0.0
  vector_math: ^2.1.4
  geocoding: ^3.0.0
  flutter_svg: ^2.0.17
  vibration: ^3.1.3
  just_audio: ^0.9.46
  just_audio_media_kit: ^2.1.0
  just_audio_background: ^0.0.1-beta.17
  audio_video_progress_bar: ^2.0.3
  dartx: ^1.2.0
  fluttertoast: ^8.2.12
  url_launcher: ^6.3.1
  path_provider: ^2.1.5
  prayers_times: ^0.0.6
  share_plus: ^11.0.0
  clipboard: ^0.1.3
  flutter_html: ^3.0.0
  visibility_detector: ^0.4.0+2
  font_awesome_flutter: ^10.8.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  icons_launcher: ^3.0.1


flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/img/
    - assets/
    - assets/dev/
    - assets/quran_script/
    - assets/meta_data/
    - assets/address/

  fonts:
    - family: QPC_Hafs 
      fonts:
        - asset: assets/fonts/Quran/QPC Hafs font.ttf

    - family: IndopakNastaleeq
      fonts:
        - asset: assets/fonts/Quran/Indopak Nastaleeq font.ttf

    - family: NotoSans
      fonts:
        - asset: assets/fonts/App/NotoSans-Bold.ttf
          weight: 700 
        - asset: assets/fonts/App/NotoSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/App/NotoSans-Light.ttf
          weight: 300
        - asset: assets/fonts/App/NotoSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/App/NotoSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/App/NotoSans-SemiBold.ttf
          weight: 600

icons_launcher:
  image_path: "assets/img/Quran_Logo_v3.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true
  
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/img/Quran_Logo_v3.png"
  min_sdk_android: 21 