import json
import os

languages = [
    "en", "ar", "az", "bn", "de", "es", "fa", "fr", "hi", "id", "it", "ja", 
    "kk", "ko", "ms", "pa", "ps", "pt", "ru", "sw", "ta", "tr", "ur", "vi", "zh"
]

translations = {
    "explore": {
        "en": "Explore", "bn": "দেখুন", "ar": "استكشاف",
        "tr": "Keşfet", "ur": "دیکھیں", "fa": "کاوش",
        "id": "Jelajahi", "ms": "Terokai", "fr": "Explorer",
        "de": "Erkunden", "es": "Explorar", "ru": "Обзор",
        "hi": "देखें", "pt": "Explorar", "it": "Esplora",
        "ja": "探索", "ko": "탐색", "zh": "探索", "vi": "Khám phá",
        "sw": "Chunguza", "az": "Kəşf et", "kk": "Зерттеу",
        "pa": "ਖੋਜੋ", "ps": "پلټنه", "ta": "ஆராய்க"
    },
    "reminderRingtone": {
        "en": "Reminder Sound", "ar": "صوت التذكير", "az": "Xatırlatma səsi",
        "bn": "রিমাইন্ডার রিংটোন", "de": "Erinnerungston", "es": "Sonido de recordatorio",
        "fa": "صدای یادآور", "fr": "Son de rappel", "hi": "स्मरण ध्वनि",
        "id": "Suara Pengingat", "it": "Suono del promemoria", "ja": "リマインダー音",
        "kk": "Еске салу дыбысы", "ko": "알림음", "ms": "Bunyi Peringatan",
        "pa": "ਯਾਦ-ਦਹਾਨੀ ਧੁਨੀ", "ps": "د یادونې غږ", "pt": "Som de lembrete",
        "ru": "Звук напоминания", "sw": "Sauti ya Kikumbusho", "ta": "நினைவூட்டல் ஒலி",
        "tr": "Hatırlatıcı Sesi", "ur": "یاد دہانی کی آواز", "vi": "Âm thanh nhắc nhở",
        "zh": "提醒声音"
    },
    "chooseRingtone": {
        "en": "Choose Ringtone", "ar": "اختيار النغمة", "az": "Zəng melodiyası seçin",
        "bn": "রিংটোন নির্বাচন করুন", "de": "Klingelton wählen", "es": "Elegir tono",
        "fa": "انتخاب زنگ", "fr": "Choisir la sonnerie", "hi": "रिंगटोन चुनें",
        "id": "Pilih Nada Dering", "it": "Scegli suoneria", "ja": "着信音を選択",
        "kk": "Қоңырау үнін таңдаңыз", "ko": "벨소리 선택", "ms": "Pilih Nada Dering",
        "pa": "ਰਿੰਗਟੋਨ ਚੁਣੋ", "ps": "د زنګ غږ غوره کړئ", "pt": "Escolher toque",
        "ru": "Выбрать мелодию", "sw": "Chagua Mlio", "ta": "ரிங்டோனைத் தேர்ந்தெடுக்கவும்",
        "tr": "Zil Sesi Seç", "ur": "رنگ ٹون منتخب کریں", "vi": "Chọn nhạc chuông",
        "zh": "选择铃声"
    },
    "chooseRingtoneDescription": {
        "en": "Choose from system sounds or device audio",
        "ar": "اختر من أصوات النظام أو ملفات الصوت بالجهاز",
        "az": "Sistem səslərindən və ya cihaz audio fayllarından seçin",
        "bn": "সিস্টেম সাউন্ড বা ডিভাইসের অডিও থেকে বেছে নিন",
        "de": "Wählen Sie aus Systemtönen oder Gerätedateien",
        "es": "Elija entre sonidos del sistema o audio del dispositivo",
        "fa": "از صداهای سیستم یا فایل‌های صوتی دستگاه انتخاب کنید",
        "fr": "Choisissez parmi les sons du système ou l'audio de l'appareil",
        "hi": "सिस्टम ध्वनियों या डिवाइस ऑडियो से चुनें",
        "id": "Pilih dari suara sistem atau audio perangkat",
        "it": "Scegli tra i suoni di sistema o l'audio del dispositivo",
        "ja": "システム音またはデバイスの音声から選択",
        "kk": "Жүйелік дыбыстардан немесе құрылғы аудиосынан таңдаңыз",
        "ko": "시스템 소리 또는 기기 오디오에서 선택",
        "ms": "Pilih daripada bunyi sistem atau audio peranti",
        "pa": "ਸਿਸਟਮ ਧੁਨੀਆਂ ਜਾਂ ਡਿਵਾਈਸ ਆਡੀਓ ਵਿੱਚੋਂ ਚੁਣੋ",
        "ps": "د سیسټم غږونو یا د وسیلې له آډیو څخه غوره کړئ",
        "pt": "Escolha entre sons do sistema ou áudio do dispositivo",
        "ru": "Выберите из системных звуков или аудио устройства",
        "sw": "Chagua kutoka kwa sauti za mfumo au faili za sauti za kifaa",
        "ta": "கணினி ஒலிகள் அல்லது சாதன ஆடியோவிலிருந்து தேர்ந்தெடுக்கவும்",
        "tr": "Sistem seslerinden veya cihaz seslerinden seçin",
        "ur": "سسٹم کی آوازوں یا ڈیوائس کے آڈیو سے منتخب کریں",
        "vi": "Chọn từ âm thanh hệ thống hoặc âm thanh thiết bị",
        "zh": "从系统声音或设备音频中选择"
    },
    "defaultSound": {
        "en": "App Default (notification_sound.wav)",
        "ar": "افتراضي التطبيق (notification_sound.wav)",
        "az": "Tətbiq standartı (notification_sound.wav)",
        "bn": "অ্যাপ ডিফল্ট (notification_sound.wav)",
        "de": "App-Standard (notification_sound.wav)",
        "es": "Predeterminado de la app (notification_sound.wav)",
        "fa": "پیش‌فرض برنامه (notification_sound.wav)",
        "fr": "Par défaut de l'application (notification_sound.wav)",
        "hi": "ऐप डिफ़ॉल्ट (notification_sound.wav)",
        "id": "Bawaan Aplikasi (notification_sound.wav)",
        "it": "Predefinito dell'app (notification_sound.wav)",
        "ja": "アプリデフォルト (notification_sound.wav)",
        "kk": "Қолданбаның әдепкі үні (notification_sound.wav)",
        "ko": "앱 기본값 (notification_sound.wav)",
        "ms": "Lalai Aplikasi (notification_sound.wav)",
        "pa": "ਐਪ ਡਿਫੌਲਟ (notification_sound.wav)",
        "ps": "د اپلیکیشن ډیفالټ (notification_sound.wav)",
        "pt": "Padrão do aplicativo (notification_sound.wav)",
        "ru": "По умолчанию приложения (notification_sound.wav)",
        "sw": "Chaguo-msingi la Programu (notification_sound.wav)",
        "ta": "செயலி இயல்புநிலை (notification_sound.wav)",
        "tr": "Uygulama Varsayılanı (notification_sound.wav)",
        "ur": "ایپ کا ڈیفالٹ (notification_sound.wav)",
        "vi": "Mặc định ứng dụng (notification_sound.wav)",
        "zh": "应用默认 (notification_sound.wav)"
    },
    "systemNotification": {
        "en": "System Default Notification",
        "ar": "إشعار النظام الافتراضي",
        "az": "Sistem standart bildirişi",
        "bn": "সিস্টেম ডিফল্ট নোটিফিকেশন",
        "de": "Systemstandard-Benachrichtigung",
        "es": "Notificación predeterminada del sistema",
        "fa": "اعلان پیش‌فرض سیستم",
        "fr": "Notification par défaut du système",
        "hi": "सिस्टम डिफ़ॉल्ट सूचना",
        "id": "Notifikasi Bawaan Sistem",
        "it": "Notifica predefinita di sistema",
        "ja": "システム標準の通知音",
        "kk": "Жүйенің әдепкі хабарландыруы",
        "ko": "시스템 기본 알림",
        "ms": "Pemberitahuan Lalai Sistem",
        "pa": "ਸਿਸਟਮ ਡਿਫੌਲਟ ਸੂਚਨਾ",
        "ps": "د سیسټم ډیفالټ خبرتیا",
        "pt": "Notificação padrão do sistema",
        "ru": "Системное уведомление по умолчанию",
        "sw": "Taarifa Chaguomsingi ya Mfumo",
        "ta": "கணினி இயல்புநிலை அறிவிப்பு",
        "tr": "Sistem Varsayılan Bildirimi",
        "ur": "سسٹم کا ڈیفالٹ نوٹیفکیشن",
        "vi": "Thông báo mặc định của hệ thống",
        "zh": "系统默认通知"
    },
    "systemAlarm": {
        "en": "System Default Alarm",
        "ar": "منبه النظام الافتراضي",
        "az": "Sistem standart zəngli saatı",
        "bn": "সিস্টেম ডিফল্ট অ্যালার্ম",
        "de": "Systemstandard-Alarm",
        "es": "Alarma predeterminada del sistema",
        "fa": "هشدار پیش‌فرض سیستم",
        "fr": "Alarme par défaut du système",
        "hi": "सिस्टम डिफ़ॉल्ट अलार्म",
        "id": "Alarm Bawaan Sistem",
        "it": "Sveglia predefinita di sistema",
        "ja": "システム標準のアラーム音",
        "kk": "Жүйенің әдепкі оятар үні",
        "ko": "시스템 기본 알람",
        "ms": "Penggera Lalai Sistem",
        "pa": "ਸਿਸਟਮ ਡਿਫੌਲਟ ਅਲਾਰਮ",
        "ps": "د سیسټم ډیفالټ الارم",
        "pt": "Alarme padrão do sistema",
        "ru": "Системный будильник по умолчанию",
        "sw": "Kengele Chaguomsingi ya Mfumo",
        "ta": "கணினி இயல்புநிலை அலாரம்",
        "tr": "Sistem Varsayılan Alarmı",
        "ur": "سسٹم کا ڈیفالٹ الارم",
        "vi": "Báo thức mặc định của hệ thống",
        "zh": "系统默认闹钟"
    },
    "systemRingtone": {
        "en": "System Phone Ringtone",
        "ar": "نغمة الهاتف الافتراضية",
        "az": "Sistem telefon zəngi",
        "bn": "সিস্টেম ফোন রিংটোন",
        "de": "System-Telefonklingelton",
        "es": "Tono de llamada del sistema",
        "fa": "زنگ تماس سیستم",
        "fr": "Sonnerie de téléphone du système",
        "hi": "सिस्टम फ़ोन रिंगटोन",
        "id": "Nada Dering Telepon Sistem",
        "it": "Suoneria del telefono di sistema",
        "ja": "システムの着信音",
        "kk": "Жүйенің телефон қоңырауы",
        "ko": "시스템 전화 벨소리",
        "ms": "Nada Dering Telefon Sistem",
        "pa": "ਸਿਸਟਮ ਫ਼ੋਨ ਰਿੰਗਟੋਨ",
        "ps": "د سیسټم د ټیلیفون زنګ",
        "pt": "Toque de telefone do sistema",
        "ru": "Системный звонок телефона",
        "sw": "Mlio wa Simu wa Mfumo",
        "ta": "கணினி தொலைபேசி ரிங்டோன்",
        "tr": "Sistem Telefon Zil Sesi",
        "ur": "سسٹم کی فون رنگ ٹون",
        "vi": "Nhạc chuông điện thoại của hệ thống",
        "zh": "系统电话铃声"
    },
    "previewSound": {
        "en": "Preview Sound",
        "ar": "معاينة الصوت",
        "az": "Səsə qabaqcadan baxış",
        "bn": "শব্দ শুনুন",
        "de": "Ton anhören",
        "es": "Vista previa del sonido",
        "fa": "پیش‌شنیدن صدا",
        "fr": "Écouter le son",
        "hi": "ध्वनि पूर्वावलोकन",
        "id": "Pratinjau Suara",
        "it": "Ascolta anteprima",
        "ja": "サウンドを試聴",
        "kk": "Дыбысты тыңдау",
        "ko": "소리 미리듣기",
        "ms": "Pratonton Bunyi",
        "pa": "ਧੁਨੀ ਦੀ ਝਲਕ",
        "ps": "د غږ مخکتنه",
        "pt": "Ouvir prévia",
        "ru": "Прослушать звук",
        "sw": "Sikiliza Sauti",
        "ta": "ஒலியை முன்னோட்டமிடு",
        "tr": "Sesi Önizle",
        "ur": "آواز سنیں",
        "vi": "Nghe thử âm thanh",
        "zh": "试听声音"
    },
    "stopPreview": {
        "en": "Stop Preview",
        "ar": "إيقاف المعاينة",
        "az": "Önizləməni dayandırın",
        "bn": "প্লে বন্ধ করুন",
        "de": "Wiedergabe stoppen",
        "es": "Detener reproducción",
        "fa": "توقف پخش",
        "fr": "Arrêter l'écoute",
        "hi": "पूर्वावलोकन रोकें",
        "id": "Hentikan Pratinjau",
        "it": "Ferma anteprima",
        "ja": "試聴を停止",
        "kk": "Тыңдауды тоқтату",
        "ko": "미리듣기 중지",
        "ms": "Hentikan Pratonton",
        "pa": "ਝਲਕ ਰੋਕੋ",
        "ps": "مخکتنه بنده کړئ",
        "pt": "Parar prévia",
        "ru": "Остановить",
        "sw": "Acha Kusikiliza",
        "ta": "முன்னோட்டத்தை நிறுத்து",
        "tr": "Önizlemeyi Durdur",
        "ur": "بند کریں",
        "vi": "Dừng nghe thử",
        "zh": "停止试听"
    },
    "testNotification": {
        "en": "Send Test Notification",
        "ar": "إرسال إشعار تجريبي",
        "az": "Test bildirişi göndərin",
        "bn": "টেস্ট নোটিফিকেশন পাঠান",
        "de": "Testbenachrichtigung senden",
        "es": "Enviar notificación de prueba",
        "fa": "ارسال اعلان آزمایشی",
        "fr": "Envoyer une notification de test",
        "hi": "परीक्षण सूचना भेजें",
        "id": "Kirim Notifikasi Uji Coba",
        "it": "Invia notifica di prova",
        "ja": "テスト通知を送信",
        "kk": "Сынақ хабарландыруын жіберу",
        "ko": "테스트 알림 보내기",
        "ms": "Hantar Pemberitahuan Ujian",
        "pa": "ਟੈਸਟ ਸੂਚਨਾ ਭੇਜੋ",
        "ps": "ازمایښتي خبرتیا واستوئ",
        "pt": "Enviar notificação de teste",
        "ru": "Отправить тестовое уведомление",
        "sw": "Tuma Taarifa ya Jaribio",
        "ta": "சோதனை அறிவிப்பை அனுப்பவும்",
        "tr": "Test Bildirimi Gönder",
        "ur": "ٹیسٹ نوٹیفکیشن بھیجیں",
        "vi": "Gửi thông báo thử nghiệm",
        "zh": "发送测试通知"
    },
    "testNotificationSent": {
        "en": "Test notification sent! Check your notifications.",
        "ar": "تم إرسال الإشعار التجريبي! تحقق من إشعاراتك.",
        "az": "Test bildirişi göndərildi! Bildirişlərinizi yoxlayın.",
        "bn": "টেস্ট নোটিফিকেশন পাঠানো হয়েছে! আপনার নোটিফিকেশন চেক করুন।",
        "de": "Testbenachrichtigung gesendet! Überprüfen Sie Ihre Benachrichtigungen.",
        "es": "¡Notificación de prueba enviada! Revisa tus notificaciones.",
        "fa": "اعلان آزمایشی ارسال شد! اعلان‌های خود را بررسی کنید.",
        "fr": "Notification de test envoyée ! Vérifiez vos notifications.",
        "hi": "परीक्षण सूचना भेजी गई! अपनी सूचनाएं जांचें।",
        "id": "Notifikasi uji coba terkirim! Periksa notifikasi Anda.",
        "it": "Notifica di prova inviata! Controlla le tue notifiche.",
        "ja": "テスト通知を送信しました！通知を確認してください。",
        "kk": "Сынақ хабарландыруы жіберілді! Хабарландыруларыңызды тексеріңіз.",
        "ko": "테스트 알림이 전송되었습니다! 알림을 확인하세요.",
        "ms": "Pemberitahuan ujian dihantar! Semak pemberitahuan anda.",
        "pa": "ਟੈਸਟ ਸੂਚਨਾ ਭੇਜੀ ਗਈ! ਆਪਣੀਆਂ ਸੂਚਨਾਵਾਂ ਦੀ ਜਾਂਚ ਕਰੋ।",
        "ps": "ازمایښتي خبرتیا واستول شوه! خپلې خبرتیاوې وګورئ.",
        "pt": "Notificação de teste enviada! Verifique suas notificações.",
        "ru": "Тестовое уведомление отправлено! Проверьте панель уведомлений.",
        "sw": "Taarifa ya jaribio imetumwa! Angalia taarifa zako.",
        "ta": "சோதனை அறிவிப்பு அனுப்பப்பட்டது! உங்கள் அறிவிப்புகளைச் சரிபார்க்கவும்.",
        "tr": "Test bildirimi gönderildi! Bildirimlerinizi kontrol edin.",
        "ur": "ٹیسٹ نوٹیفکیشن بھیج دیا گیا! اپنے نوٹیفکیشنز چیک کریں۔",
        "vi": "Đã gửi thông báo thử nghiệm! Kiểm tra thông báo của bạn.",
        "zh": "测试通知已发送！请查看您的通知。"
    },
    "quickPresets": {
        "en": "Quick Presets",
        "ar": "خيارات سريعة",
        "az": "Sürətli seçimlər",
        "bn": "কুইক প্রিসেট",
        "de": "Schnellauswahl",
        "es": "Ajustes rápidos",
        "fa": "گزینه‌های سریع",
        "fr": "Sélection rapide",
        "hi": "त्वरित प्रीसेट",
        "id": "Pilihan Cepat",
        "it": "Preimpostazioni rapide",
        "ja": "クイックプリセット",
        "kk": "Жылдам таңдаулар",
        "ko": "빠른 사전 설정",
        "ms": "Pratetap Pantas",
        "pa": "ਤੁਰੰਤ ਪ੍ਰੀਸੈਟਸ",
        "ps": "ګړندي اختیارونه",
        "pt": "Predefinições rápidas",
        "ru": "Быстрый выбор",
        "sw": "Chaguo za Haraka",
        "ta": "விரைவு முன்னமைவுகள்",
        "tr": "Hızlı Önayarlar",
        "ur": "فوری ترتیبات",
        "vi": "Cài đặt nhanh",
        "zh": "快速预设"
    },
    "reminderModeOff": {
        "en": "Off", "ar": "إيقاف", "az": "Bağlı", "bn": "বন্ধ",
        "de": "Aus", "es": "Desactivado", "fa": "خاموش", "fr": "Désactivé",
        "hi": "बंद", "id": "Mati", "it": "Disattivato", "ja": "オフ",
        "kk": "Өшірулі", "ko": "꺼짐", "ms": "Mati", "pa": "ਬੰਦ",
        "ps": "بند", "pt": "Desligado", "ru": "Выкл", "sw": "Zima",
        "ta": "முடக்கு", "tr": "Kapalı", "ur": "بند", "vi": "Tắt", "zh": "关闭"
    },
    "reminderModeNotification": {
        "en": "Notification", "ar": "إشعار", "az": "Bildiriş", "bn": "নোটিফিকেশন",
        "de": "Benachrichtigung", "es": "Notificación", "fa": "اعلان", "fr": "Notification",
        "hi": "अधिसूचना", "id": "Notifikasi", "it": "Notifica", "ja": "通知",
        "kk": "Хабарландыру", "ko": "알림", "ms": "Pemberitahuan", "pa": "ਸੂਚਨਾ",
        "ps": "خبرتیا", "pt": "Notificação", "ru": "Уведомление", "sw": "Arifa",
        "ta": "அறிவிப்பு", "tr": "Bildirim", "ur": "اطلاع", "vi": "Thông báo", "zh": "通知"
    },
    "reminderModeAlarm": {
        "en": "Alarm", "ar": "منبه", "az": "Zəngli saat", "bn": "অ্যালার্ম",
        "de": "Wecker", "es": "Alarma", "fa": "هشدار", "fr": "Alarme",
        "hi": "अलार्म", "id": "Alarm", "it": "Sveglia", "ja": "アラーム",
        "kk": "Оятқыш", "ko": "알람", "ms": "Penggera", "pa": "ਅਲਾਰਮ",
        "ps": "الارم", "pt": "Alarme", "ru": "Будильник", "sw": "Kengele",
        "ta": "அலாரம்", "tr": "Alarm", "ur": "الارم", "vi": "Báo thức", "zh": "闹钟"
    },
    "testAlarm": {
        "en": "Test Alarm", "ar": "تجربة المنبه", "az": "Zəngli saatı sına", "bn": "অ্যালার্ম পরীক্ষা করুন",
        "de": "Wecker testen", "es": "Probar alarma", "fa": "آزمایش هشدار", "fr": "Tester l'alarme",
        "hi": "अलार्म परीक्षण", "id": "Uji Alarm", "it": "Testa sveglia", "ja": "アラームテスト",
        "kk": "Оятқышты тексеру", "ko": "알람 테스트", "ms": "Uji Penggera", "pa": "ਅਲਾਰਮ ਪਰਖੋ",
        "ps": "الارم وازموئئ", "pt": "Testar alarme", "ru": "Тест будильника", "sw": "Jaribu Kengele",
        "ta": "அலாரத்தை சோதிக்கவும்", "tr": "Alarmı Test Et", "ur": "الارم آزمائیں", "vi": "Kiểm tra báo thức", "zh": "测试闹钟"
    },
    "testAlarmSent": {
        "en": "Full-screen alarm test sent", "ar": "تم إرسال تجربة المنبه بملء الشاشة", "az": "Tam ekran zəngli saat testi göndərildi", "bn": "ফুল-স্ক্রিন অ্যালার্ম টেস্ট পাঠানো হয়েছে",
        "de": "Vollbild-Alarmtest gesendet", "es": "Prueba de alarma de pantalla completa enviada", "fa": "آزمایش هشدار تمام صفحه ارسال شد", "fr": "Test d'alarme plein écran envoyé",
        "hi": "फुल-स्क्रीन अलार्म टेस्ट भेजा गया", "id": "Uji alarm layar penuh terkirim", "it": "Test sveglia a schermo intero inviato", "ja": "全画面アラームテストを送信しました",
        "kk": "Толық экранды оятқыш сынағы жіберілді", "ko": "전체 화면 알람 테스트 전송됨", "ms": "Ujian penggera skrin penuh dihantar", "pa": "ਫੁੱਲ-ਸਕ੍ਰੀਨ ਅਲਾਰਮ ਟੈਸਟ ਭੇਜਿਆ ਗਿਆ",
        "ps": "د بشپړ سکرین د الارم ازموینه واستول شوه", "pt": "Teste de alarme em tela cheia enviado", "ru": "Тест полноэкранного будильника отправлен", "sw": "Jaribio la kengele ya skrini nzima limetumwa",
        "ta": "முழுத் திரை அலார சோதனை அனுப்பப்பட்டது", "tr": "Tam ekran alarm testi gönderildi", "ur": "مکمل اسکرین الارم ٹیسٹ بھیج دیا گیا", "vi": "Đã gửi kiểm tra báo thức toàn màn hình", "zh": "已发送全屏闹钟测试"
    },
    "stopAlarm": {
        "en": "Stop Alarm", "ar": "إيقاف المنبه", "az": "Zəngli saatı saxla", "bn": "অ্যালার্ম বন্ধ করুন",
        "de": "Wecker stoppen", "es": "Detener alarma", "fa": "توقف هشدار", "fr": "Arrêter l'alarme",
        "hi": "अलार्म बंद करें", "id": "Hentikan Alarm", "it": "Ferma sveglia", "ja": "アラーム停止",
        "kk": "Оятқышты тоқтату", "ko": "알람 중지", "ms": "Hentikan Penggera", "pa": "ਅਲਾਰਮ ਰੋਕੋ",
        "ps": "الارم بند کړئ", "pt": "Parar alarme", "ru": "Остановить будильник", "sw": "Simamisha Kengele",
        "ta": "அலாரத்தை நிறுத்து", "tr": "Alarmı Durdur", "ur": "الارم بند کریں", "vi": "Dừng báo thức", "zh": "停止闹钟"
    },
    "snooze": {
        "en": "Snooze", "ar": "غفوة", "az": "Təxirə sal", "bn": "স্নুজ",
        "de": "Schlummern", "es": "Posponer", "fa": "تعویق", "fr": "Répéter",
        "hi": "स्नूज़", "id": "Tunda", "it": "Posponi", "ja": "スヌーズ",
        "kk": "Кейінге қалдыру", "ko": "스누즈", "ms": "Tunda", "pa": "ਸਨੂਜ਼",
        "ps": "ځنډول", "pt": "Soneca", "ru": "Отложить", "sw": "Ahirisha",
        "ta": "ஸ்னூஸ்", "tr": "Ertele", "ur": "اسنوز", "vi": "Báo lại", "zh": "稍后提醒"
    },
    "snoozed10Min": {
        "en": "Snoozed for 10 minutes", "ar": "تم التفعيل لـ 10 دقائق", "az": "10 dəqiqə təxirə salındı", "bn": "১০ মিনিটের জন্য স্নুজ করা হয়েছে",
        "de": "Für 10 Minuten geschlummert", "es": "Pospuesto por 10 minutos", "fa": "برای ۱۰ دقیقه به تعویق افتاد", "fr": "Répété pour 10 minutes",
        "hi": "10 मिनट के लिए स्नूज़ किया गया", "id": "Ditunda selama 10 menit", "it": "Posposto per 10 minuti", "ja": "10分間スヌーズしました",
        "kk": "10 минутқа кейінге қалдырылды", "ko": "10분 동안 스누즈됨", "ms": "Ditunda selama 10 minit", "pa": "10 ਮਿੰਟਾਂ ਲਈ ਸਨੂਜ਼ ਕੀਤਾ ਗਿਆ",
        "ps": "د ۱۰ دقیقو لپاره وځنډول شو", "pt": "Adiado por 10 minutos", "ru": "Отложено на 10 минут", "sw": "Imeahirishwa kwa dakika 10",
        "ta": "10 நிமிடங்களுக்கு ஒத்திவைக்கப்பட்டது", "tr": "10 dakika ertelendi", "ur": "10 منٹ کے لیے اسنوز کیا گیا", "vi": "Đã báo lại trong 10 phút", "zh": "已稍后提醒10分钟"
    },
    "fullScreenAlarmPermission": {
        "en": "Full-Screen Alarm Permission", "ar": "إذن المنبه بملء الشاشة", "az": "Tam ekran zəngli saat icazəsi", "bn": "ফুল-স্ক্রিন অ্যালার্ম অনুমতি",
        "de": "Vollbild-Alarm-Berechtigung", "es": "Permiso de alarma de pantalla completa", "fa": "مجوز هشدار تمام صفحه", "fr": "Autorisation d'alarme plein écran",
        "hi": "फुल-स्क्रीन अलार्म अनुमति", "id": "Izin Alarm Layar Penuh", "it": "Autorizzazione sveglia a schermo intero", "ja": "全画面アラーム権限",
        "kk": "Толық экранды оятқыш рұқсаты", "ko": "전체 화면 알람 권한", "ms": "Kebenaran Penggera Skrin Penuh", "pa": "ਫੁੱਲ-ਸਕ੍ਰੀਨ ਅਲਾਰਮ ਆਗਿਆ",
        "ps": "د بشپړ سکرین د الارم اجازه", "pt": "Permissão de alarme em tela cheia", "ru": "Разрешение на полноэкранный будильник", "sw": "Ruhusa ya Kengele ya Skrini Nzima",
        "ta": "முழுத் திரை அலார அனுமதி", "tr": "Tam Ekran Alarm İzni", "ur": "فل اسکرین الارم کی اجازت", "vi": "Quyền báo thức toàn màn hình", "zh": "全屏闹钟权限"
    },
    "fullScreenAlarmPermissionDesc": {
        "en": "Allow alarms to wake up the screen when your phone is locked", "ar": "السماح للمنبه بإيقاظ الشاشة عندما يكون الهاتف مقفلاً", "az": "Telefon kilitli olduqda zəngli saatın ekranı oyatmasına icazə verin", "bn": "ফোন লক থাকা অবস্থায় অ্যালার্মকে স্ক্রিন জাগানোর অনুমতি দিন",
        "de": "Erlauben Sie dem Wecker, den Bildschirm bei gesperrtem Telefon zu aktivieren", "es": "Permitir que las alarmas activen la pantalla cuando el teléfono está bloqueado", "fa": "اجازه دهید هشدارها هنگام قفل بودن گوشی صفحه را روشن کنند", "fr": "Autoriser les alarmes à réveiller l'écran lorsque le téléphone est verrouillé",
        "hi": "फ़ोन लॉक होने पर अलार्म को स्क्रीन जगाने की अनुमति दें", "id": "Izinkan alarm mengaktifkan layar saat ponsel terkunci", "it": "Consenti alle sveglie di riattivare lo schermo quando il telefono è bloccato", "ja": "端末がロックされている時にアラームが画面を起動することを許可",
        "kk": "Телефон құлыптаулы болғанда оятқышқа экранды оятуға рұқсат етіңіз", "ko": "휴대폰이 잠겨 있을 때 알람이 화면을 켜도록 허용", "ms": "Benarkan penggera menghidupkan skrin apabila telefon dikunci", "pa": "ਫੋਨ ਲੌਕ ਹੋਣ 'ਤੇ ਅਲਾਰਮ ਨੂੰ ਸਕ੍ਰੀਨ ਜਗਾਉਣ ਦੀ ਆਗਿਆ ਦਿਓ",
        "ps": "الارم ته اجازه ورکړئ کله چې ټلیفون قفل وي سکرین فعال کړي", "pt": "Permitir que os alarmes ativem a tela quando o telefone estiver bloqueado", "ru": "Разрешить будильникам включать экран при заблокированном телефоне", "sw": "Ruhusu kengele kuamsha skrini wakati simu imefungwa",
        "ta": "தொலைபேசி பூட்டப்பட்டிருக்கும் போது அலாரங்கள் திரையை எழுப்ப அனுமதிக்கவும்", "tr": "Telefon kilitliyken alarmların ekranı uyandırmasına izin verin", "ur": "فون لاک ہونے پر الارم کو اسکرین آن کرنے کی اجازت دیں", "vi": "Cho phép báo thức đánh thức màn hình khi điện thoại bị khóa", "zh": "允许闹钟在手机锁定时唤醒屏幕"
    },
    "grantPermission": {
        "en": "Grant Permission", "ar": "منح الإذن", "az": "İcazə verin", "bn": "অনুমতি দিন",
        "de": "Berechtigung erteilen", "es": "Conceder permiso", "fa": "اعطای مجوز", "fr": "Accorder l'autorisation",
        "hi": "अनुमति दें", "id": "Beri Izin", "it": "Concedi autorizzazione", "ja": "権限を許可",
        "kk": "Рұқсат беру", "ko": "권한 허용", "ms": "Beri Kebenaran", "pa": "ਆਗਿਆ ਦਿਓ",
        "ps": "اجازه ورکړئ", "pt": "Conceder permissão", "ru": "Предоставить разрешение", "sw": "Toa Ruhusa",
        "ta": "அனுமதி கொடுங்கள்", "tr": "İzin Ver", "ur": "اجازت دیں", "vi": "Cấp quyền", "zh": "授予权限"
    },
    "adhanSound": {
        "en": "Authentic Adhan", "ar": "أذان أصيل", "az": "Həqiqi Azan", "bn": "আযান",
        "de": "Authentischer Adhan", "es": "Adhan auténtico", "fa": "اذان اصیل", "fr": "Adhan authentique",
        "hi": "अज़ान", "id": "Adzan Otentik", "it": "Adhan autentico", "ja": "アザーン",
        "kk": "Азан", "ko": "아잔", "ms": "Azan Autentik", "pa": "ਅਜ਼ਾਨ",
        "ps": "اذان", "pt": "Adhan autêntico", "ru": "Азан", "sw": "Adhana Halisi",
        "ta": "பாங்கு ஒலி", "tr": "Özgün Ezan", "ur": "اذان", "vi": "Âm Adhan", "zh": "宣礼声"
    },
    "batteryOptimizationTitle": {
        "en": "Battery Optimization Exemption", "ar": "إعفاء تحسين البطارية", "az": "Batareya optimallaşdırma istisnası", "bn": "ব্যাটারি অপ্টিমাইজেশন ছাড়",
        "de": "Ausnahme von Akku-Optimierung", "es": "Exención de optimización de batería", "fa": "معافیت بهینه‌سازی باتری", "fr": "Exemption d'optimisation de batterie",
        "hi": "बैटरी ऑप्टিमाइज़ेशन छूट", "id": "Pengecualian Optimasi Baterai", "it": "Esenzione ottimizzazione batteria", "ja": "バッテリー最適化の除外",
        "kk": "Батареяны оңтайландырудан босату", "ko": "배터리 최적화 예외", "ms": "Pengecualian Pengoptimuman Bateri", "pa": "ਬੈਟਰੀ ਓਪਟੀਮਾਈਜ਼ੇਸ਼ਨ ਛੋਟ",
        "ps": "د بیټرۍ اصلاح څخه معافیت", "pt": "Isenção de otimização de bateria", "ru": "Исключение из оптимизации батареи", "sw": "Msamaha wa Betri",
        "ta": "பேட்டரி தேர்வு விலக்கு", "tr": "Pil Optimizasyonu Muafiyeti", "ur": "بیٹری آپٹیمائزیشن چھوٹ", "vi": "Miễn trừ tối ưu hóa pin", "zh": "电池优化豁免"
    },
    "batteryOptimizationDesc": {
        "en": "Allow app to run in background to ensure prayer alarms trigger on time on your device",
        "ar": "السماح للتطبيق بالعمل في الخلفية لضمان عمل تنبيهات الصلاة في الوقت المحدد",
        "az": "Namaz zənglərinin vaxtında çalması üçün tətbiqin arxa fonda işləməsinə icazə verin",
        "bn": "আপনার ডিভাইসে যথাসময়ে নামাজের অ্যালার্ম বাজাতে ব্যাকগ্রাউন্ডে চলার অনুমতি দিন",
        "de": "Ermöglichen Sie der App, im Hintergrund zu laufen, um pünktliche Gebetsalarme sicherzustellen",
        "es": "Permitir que la app se ejecute en segundo plano para garantizar alarmas de oración puntuales",
        "fa": "اجازه دهید برنامه در پس‌زمینه اجرا شود تا هشدارهای نماز به‌موقع به صدا درآیند",
        "fr": "Autoriser l'application en arrière-plan pour garantir les alarmes de prière à l'heure",
        "hi": "समय पर नमाज़ अलार्म सुनिश्चित करने के लिए ऐप को बैकग्राउंड में चलने दें",
        "id": "Izinkan aplikasi berjalan di latar belakang agar alarm sholat berbunyi tepat waktu",
        "it": "Consenti all'app di funzionare in background per garantire le sveglie di preghiera puntuali",
        "ja": "礼拝アラームが定刻に鳴るようバックグラウンド実行を許可",
        "kk": "Намаз оятқыштарының уақытында соғылуын қамтамасыз ету үшін қолданбаның фонда жұмыс істеуіне рұқсат беріңіз",
        "ko": "기도 알람이 제시간에 울리도록 백그라운드 실행을 허용하세요",
        "ms": "Benarkan aplikasi berjalan di latar belakang untuk memastikan penggera solat berbunyi tepat pada masanya",
        "pa": "ਨਮਾਜ਼ ਦੇ ਅਲਾਰਮ ਸਮੇਂ ਸਿਰ ਵੱਜਣ ਲਈ ਐਪ ਨੂੰ ਬੈਕਗ੍ਰਾਊਂਡ ਵਿੱਚ ਚੱਲਣ ਦਿਓ",
        "ps": "د لمانځه الارمونه په وخت کار کولو لپاره اپلیکیشن ته په شالید کې د چلېدو اجازه ورکړئ",
        "pt": "Permitir que o aplicativo funcione em segundo plano para garantir alarmes de oração no horário",
        "ru": "Разрешите работу в фоновом режиме для точного срабатывания будильников намаза",
        "sw": "Ruhusu programu ifanye kazi chinichini ili kuhakikisha kengele za sala zinalia kwa wakati",
        "ta": "தொழுகை அலாரங்கள் சரியான நேரத்தில் ஒலிக்க பயன்பாட்டைப் பின்னணியில் இயக்க அனுமதிக்கவும்",
        "tr": "Namaz alarmlarının vaktinde çalmasını sağlamak için uygulamanın arka planda çalışmasına izin verin",
        "ur": "نماز کے الارم وقت پر بجنے کو یقینی بنانے کے لیے ایپ کو پس منظر میں چلنے کی اجازت دیں",
        "vi": "Cho phép ứng dụng chạy dưới nền để đảm bảo báo thức giờ cầu nguyện kích hoạt đúng giờ",
        "zh": "允许应用在后台运行，以确保礼拜闹钟准时触发"
    },
    "prayerGuidanceSetupTitle": {
        "en": "Prayer Reminders Guide & Setup", "ar": "دليل وإعداد تنبيهات الصلاة", "az": "Namaz xatırlatmaları bələdçisi və quraşdırma", "bn": "নামাজের রিমাইন্ডার গাইড ও সেটআপ",
        "de": "Gebetserinnerungs-Leitfaden & Einrichtung", "es": "Guía y configuración de recordatorios de oración", "fa": "راهنما و تنظیمات یادآورهای نماز", "fr": "Guide et configuration des rappels de prière",
        "hi": "नमाज़ अनुस्मारक गाइड और सेटअप", "id": "Panduan & Pengaturan Pengingat Sholat", "it": "Guida e configurazione promemoria di preghiera", "ja": "礼拝リマインダーガイド＆設定",
        "kk": "Намаз еске салғыштарының нұсқаулығы және баптауы", "ko": "기도 알림 가이드 및 설정", "ms": "Panduan & Tetapan Peringatan Solat", "pa": "ਨਮਾਜ਼ ਰੀਮਾਈਂਡਰ ਗਾਈਡ ਅਤੇ ਸੈੱਟਅੱਪ",
        "ps": "د لمانځه یادونې لارښود او تنظیم", "pt": "Guia e configuração de lembretes de oração", "ru": "Руководство и настройка напоминаний намаза", "sw": "Mwongozo na Usanidi wa Vikumbusho vya Sala",
        "ta": "தொழுகை நினைவூட்டல் வழிகாட்டி மற்றும் அமைப்பு", "tr": "Namaz Hatırlatıcı Rehberi ve Kurulumu", "ur": "نماز یاد دہانی گائیڈ اور سیٹ اپ", "vi": "Hướng dẫn & Thiết lập nhắc nhở cầu nguyện", "zh": "礼拜提醒指南与设置"
    },
    "prayerGuidanceSetupDesc": {
        "en": "Configure waking alarms, Adhan sound, and permissions", "ar": "تكوين منبهات الاستيقاظ وصوت الأذان والأذونات", "az": "Oyatma zəngləri, azan səsi və icazələri tənzimləyin", "bn": "অ্যালার্ম, আযানের শব্দ এবং প্রয়োজনীয় অনুমতি কনফিগার করুন",
        "de": "Weckalarme, Adhan-Ton und Berechtigungen konfigurieren", "es": "Configurar alarmas, sonido de Adhan y permisos", "fa": "پیکربندی هشدارهای بیدارباش، صدای اذان و مجوزها", "fr": "Configurer les alarmes de réveil, le son de l'Adhan et les autorisations",
        "hi": "अलार्म, अज़ान ध्वनि और अनुमतियाँ कॉन्फ़िगर करें", "id": "Konfigurasi alarm bangun, suara adzan, dan izin", "it": "Configura le sveglie, il suono dell'Adhan e i permessi", "ja": "起床アラーム、アザーン音、権限を設定",
        "kk": "Оятқыштарды, азан дыбысын және рұқсаттарды баптаңыз", "ko": "기상 알람, 아잔 소리 및 권한 구성", "ms": "Konfigurasikan penggera bangun, bunyi azan dan kebenaran", "pa": "ਅਲਾਰਮ, ਅਜ਼ਾਨ ਆਵਾਜ਼ ਅਤੇ ਇਜਾਜ਼ਤਾਂ ਸੈੱਟ ਕਰੋ",
        "ps": "د ویښېدو الارمونه، د اذان غږ او اجازې تنظیم کړئ", "pt": "Configurar alarmes de despertar, som do Adhan e permissões", "ru": "Настройте будильники, звук азана и разрешения", "sw": "Sanidi kengele za kuamka, sauti ya adhana na ruhusa",
        "ta": "விழித்தெழும் அலாரங்கள், பாங்கு ஒலி மற்றும் அனுமதிகளை உள்ளமைக்கவும்", "tr": "Uyanma alarmlarını, ezan sesini ve izinleri yapılandırın", "ur": "بیدار کرنے والے الارم، اذان کی آواز اور اجازتیں ترتیب دیں", "vi": "Định cấu hình báo thức thức dậy, âm thanh Adhan và quyền", "zh": "配置唤醒闹钟、宣礼声和权限"
    },
    "neverMissAPrayer": {
        "en": "Never Miss a Prayer", "ar": "لا تفوت أي صلاة", "az": "Heç bir namazı qaçırmayın", "bn": "কোনো নামাজ যেন বাদ না পড়ে",
        "de": "Verpassen Sie kein Gebet", "es": "Nunca te pierdas una oración", "fa": "هرگز نمازی را از دست ندهید", "fr": "Ne manquez jamais une prière",
        "hi": "कोई भी नमाज़ न छोड़ें", "id": "Jangan Pernah Lewatkan Sholat", "it": "Non perdere mai una preghiera", "ja": "お祈りを見逃さない",
        "kk": "Ешбір намазды жіберіп алмаңыз", "ko": "기도를 놓치지 마세요", "ms": "Jangan Lepaskan Solat", "pa": "ਕਦੇ ਵੀ ਨਮਾਜ਼ ਨਾ ਛੱਡੋ",
        "ps": "هیڅ لمونځ مه قضا کوئ", "pt": "Nunca perca uma oração", "ru": "Не пропускайте намаз", "sw": "Usikose Sala Kamwe",
        "ta": "எந்தத் தொழுகையையும் தவறவிடாதீர்கள்", "tr": "Hiçbir Namazı Kaçırmayın", "ur": "کبھی بھی نماز نہ چھوڑیں", "vi": "Không bao giờ bỏ lỡ giờ cầu nguyện", "zh": "绝不错过任何礼拜"
    },
    "prayerGuidanceHeaderDesc": {
        "en": "Choose between waking Full-Screen Alarms with the Adhan or gentle Heads-Up Notifications",
        "ar": "اختر بين منبه ملء الشاشة مع الأذان أو إشعارات لطيفة",
        "az": "Azanlı tam ekran zəngləri və ya mülayim bildirişlər arasında seçim edin",
        "bn": "আযানসহ ফুল-স্ক্রিন অ্যালার্ম অথবা হালকা নোটিফিকেশনের মধ্যে বেছে নিন",
        "de": "Wählen Sie zwischen Vollbild-Alarmen mit Adhan oder sanften Benachrichtigungen",
        "es": "Elija entre alarmas de pantalla completa con el Adhan o notificaciones suaves",
        "fa": "بین هشدارهای تمام‌صفحه با اذان یا اعلان‌های ملایم انتخاب کنید",
        "fr": "Choisissez entre des alarmes plein écran avec l'Adhan ou des notifications discrètes",
        "hi": "अज़ान के साथ फुल-स्क्रीन अलार्म या सौम्य सूचनाओं में से चुनें",
        "id": "Pilih antara Alarm Layar Penuh dengan Adzan atau Notifikasi Lembut",
        "it": "Scegli tra sveglie a schermo intero con l'Adhan o notifiche discrete",
        "ja": "アザーン付きの全画面アラームか穏やかな通知を選択",
        "kk": "Азанмен толық экранды оятқыштар немесе жұмсақ хабарландырулар арасында таңдаңыз",
        "ko": "아잔이 포함된 전체 화면 알람 또는 부드러운 알림 중에서 선택하세요",
        "ms": "Pilih antara Penggera Skrin Penuh dengan Azan atau Pemberitahuan Lembut",
        "pa": "ਅਜ਼ਾਨ ਵਾਲੇ ਫੁੱਲ-ਸਕ੍ਰੀਨ ਅਲਾਰਮ ਜਾਂ ਹਲਕੇ ਨੋਟੀਫਿਕੇਸ਼ਨਾਂ ਵਿੱਚੋਂ ਚੁਣੋ",
        "ps": "د اذان سره د بشپړ سکرین الارمونو یا نرم خبرتیاوو ترمنځ غوره کړئ",
        "pt": "Escolha entre alarmes de tela cheia com o Adhan ou notificações suaves",
        "ru": "Выберите между полноэкранным будильником с азаном или мягкими уведомлениями",
        "sw": "Chagua kati ya kengele za skrini nzima zenye adhana au arifa za upole",
        "ta": "பாங்கு ஒலியுடன் கூடிய முழுத்திரை அலாரங்கள் அல்லது அறிவிப்புகளுக்கு இடையே தேர்வு செய்யவும்",
        "tr": "Ezanlı Tam Ekran Alarmlar veya hafif bildirimler arasında seçim yapın",
        "ur": "اذان کے ساتھ فل اسکرین الارم یا ہلکے نوٹیفکیشن میں سے انتخاب کریں",
        "vi": "Chọn giữa Báo thức toàn màn hình với Adhan hoặc Thông báo nhẹ nhàng",
        "zh": "在带宣礼声的全屏闹钟或温和通知之间进行选择"
    },
    "howRemindersWork": {
        "en": "How Reminders Work", "ar": "كيف تعمل التنبيهات", "az": "Xatırlatmalar necə işləyir", "bn": "রিমাইন্ডার কীভাবে কাজ করে",
        "de": "Wie Erinnerungen funktionieren", "es": "Cómo funcionan los recordatorios", "fa": "نحوه کارکرد یادآورها", "fr": "Fonctionnement des rappels",
        "hi": "अनुस्मारक कैसे काम करते हैं", "id": "Cara Kerja Pengingat", "it": "Come funzionano i promemoria", "ja": "リマインダーの仕組み",
        "kk": "Еске салғыштар қалай жұмыс істейді", "ko": "알림 작동 방식", "ms": "Bagaimana Peringatan Berfungsi", "pa": "ਰੀਮਾਈਂਡਰ ਕਿਵੇਂ ਕੰਮ ਕਰਦੇ ਹਨ",
        "ps": "یادونې څنګه کار کوي", "pt": "Como funcionam os lembretes", "ru": "Как работают напоминания", "sw": "Jinsi Vikumbusho Vinavyofanya Kazi",
        "ta": "நினைவூட்டல்கள் எவ்வாறு செயல்படுகின்றன", "tr": "Hatırlatıcılar Nasıl Çalışır", "ur": "یاد دہانیاں کیسے کام کرتی ہیں", "vi": "Cách lời nhắc hoạt động", "zh": "提醒如何工作"
    },
    "fullScreenAlarmModeTitle": {
        "en": "Full-Screen Alarm", "ar": "منبه ملء الشاشة", "az": "Tam ekran zəngli saat", "bn": "ফুল-স্ক্রিন অ্যালার্ম",
        "de": "Vollbild-Alarm", "es": "Alarma de pantalla completa", "fa": "هشدار تمام‌صفحه", "fr": "Alarme plein écran",
        "hi": "फुल-स्क्रीन अलार्म", "id": "Alarm Layar Penuh", "it": "Sveglia a schermo intero", "ja": "全画面アラーム",
        "kk": "Толық экранды оятқыш", "ko": "전체 화면 알람", "ms": "Penggera Skrin Penuh", "pa": "ਫੁੱਲ-ਸਕ੍ਰੀਨ ਅਲਾਰਮ",
        "ps": "د بشپړ سکرین الارم", "pt": "Alarme em tela cheia", "ru": "Полноэкранный будильник", "sw": "Kengele ya Skrini Nzima",
        "ta": "முழுத் திரை அலாரம்", "tr": "Tam Ekran Alarm", "ur": "فل اسکرین الارم", "vi": "Báo thức toàn màn hình", "zh": "全屏闹钟"
    },
    "fullScreenAlarmModeDesc": {
        "en": "Wakes your screen over lockscreen with the Adhan, Arabic calligraphy, and Stop/Snooze buttons. Perfect for Fajr.",
        "ar": "يوقظ الشاشة فوق شاشة القفل مع الأذان والخط وأزرار الإيقاف/الغفوة. مثالي للفجر.",
        "az": "Ekranı kilid ekranı üzərində azan və xəttatlıqla oyadır. Sübh namazı üçün idealdır.",
        "bn": "লকস্ক্রিনের উপর আযান, ক্যালিগ্রাফি এবং স্টপ/স্নুজ বাটনসহ স্ক্রিন জাগায়। ফজরের জন্য অত্যন্ত উপযোগী।",
        "de": "Aktiviert den Bildschirm über dem Sperrbildschirm mit Adhan, Kalligrafie und Stopp/Schlummern. Perfekt für Fadschr.",
        "es": "Activa la pantalla sobre el bloqueo con el Adhan, caligrafía y Parar/Posponer. Ideal para Fajr.",
        "fa": "صفحه را روی صفحه قفل با اذان، خطاطی و توقف/تعویق روشن می‌کند. عالی برای فجر.",
        "fr": "Réveille l'écran sur le verrouillage avec l'Adhan, calligraphie et Arrêt/Répéter. Idéal pour Fajr.",
        "hi": "अज़ान, सुलेख और स्टॉप/स्नूज़ के साथ स्क्रीन को जगाता है। फ़ज्र के लिए उत्तम।",
        "id": "Membangunkan layar di atas layar kunci dengan Adzan, kaligrafi, dan Berhenti/Tunda. Sangat cocok untuk Subuh.",
        "it": "Riattiva lo schermo sopra il blocco schermo con Adhan, calligrafia e Ferma/Posponi. Perfetto per Fajr.",
        "ja": "アザーン、書道、停止/スヌーズでロック画面越しに画面を起動。ファジュルに最適。",
        "kk": "Экранды құлыптау экранының үстінен азан, каллиграфия және Тоқтату/Кейінге қалдыру арқылы оятады. Таң намазы үшін өте қолайлы.",
        "ko": "아잔, 캘리그래피 및 중지/스누즈로 잠금 화면 위로 화면을 켭니다. 파즈르에 적합합니다.",
        "ms": "Menghidupkan skrin pada skrin kunci dengan Azan, seni khat dan Berhenti/Tunda. Sesuai untuk Subuh.",
        "pa": "ਅਜ਼ਾਨ ਅਤੇ ਸਟਾਪ/ਸਨੂਜ਼ ਨਾਲ ਸਕ੍ਰੀਨ ਨੂੰ ਜਗਾਉਂਦਾ ਹੈ। ਫ਼ਜਰ ਲਈ ਸੰਪੂਰਨ।",
        "ps": "د اذان او بندولو/ځنډولو سره د سکرین څراغ روښانه کوي. د فجر لپاره مناسب.",
        "pt": "Ativa a tela sobre o bloqueio com o Adhan, caligrafia e Parar/Soneca. Perfeito para Fajr.",
        "ru": "Включает экран поверх блокировки с азаном, каллиграфией и кнопками. Идеально для Фаджра.",
        "sw": "Huamsha skrini juu ya skrini iliyofungwa kwa adhana na vitufe. Nzuri kwa Alfajiri.",
        "ta": "பாங்கு ஒலி மற்றும் நிறுத்து/ஸ்னூஸ் பொத்தான்களுடன் திரையை எழுப்புகிறது. ஃபஜ்ருக்கு ஏற்றது.",
        "tr": "Ekranı kilit ekranı üzerinden ezan, hat sanatı ve Durdur/Ertele ile uyandırır. Sabah namazı için idealdir.",
        "ur": "لاک اسکرین پر اذان، خطاطی اور بند/اسنوز کے ساتھ اسکرین روشن کرتا ہے۔ فجر کے لیے بہترین۔",
        "vi": "Bật màn hình trên màn hình khóa với Adhan và nút Dừng/Báo lại. Lý tưởng cho giờ Fajr.",
        "zh": "在锁屏上以宣礼声、书法和停止/稍后提醒唤醒屏幕。非常适合晨礼。"
    },
    "gentleNotificationModeTitle": {
        "en": "Gentle Notification", "ar": "إشعار لطيف", "az": "Mülayim bildiriş", "bn": "হালকা নোটিফিকেশন",
        "de": "Sanfte Benachrichtigung", "es": "Notificación suave", "fa": "اعلان ملایم", "fr": "Notification discrète",
        "hi": "सौम्य सूचना", "id": "Notifikasi Lembut", "it": "Notifica discreta", "ja": "穏やかな通知",
        "kk": "Жұмсақ хабарландыру", "ko": "부드러운 알림", "ms": "Pemberitahuan Lembut", "pa": "ਹਲਕਾ ਨੋਟੀਫਿਕੇਸ਼ਨ",
        "ps": "نرم خبرتیا", "pt": "Notificação suave", "ru": "Мягкое уведомление", "sw": "Arifa ya Upole",
        "ta": "மென்மையான அறிவிப்பு", "tr": "Hafif Bildirim", "ur": "ہلکی اطلاع", "vi": "Thông báo nhẹ nhàng", "zh": "温和通知"
    },
    "gentleNotificationModeDesc": {
        "en": "Standard notification banner with reminder sound. Non-intrusive and ideal for work hours.",
        "ar": "شعار إشعار قياسي مع صوت تذكير. غير مزعج ومثالي لساعات العمل.",
        "az": "Xatırlatma səsi olan standart bildiriş. İş saatları üçün idealdır.",
        "bn": "রিমাইন্ডার সাউন্ডসহ সাধারণ নোটিফিকেশন ব্যানার। কাজের সময়ের জন্য উপযুক্ত।",
        "de": "Standard-Banner mit Ton. Unaufdringlich und ideal für Arbeitszeiten.",
        "es": "Banner estándar con sonido. No intrusivo e ideal para horas de trabajo.",
        "fa": "بنر اعلان استاندارد با صدا. بدون مزاحمت و مناسب ساعت کاری.",
        "fr": "Bannière standard avec son. Discrète et idéale pendant le travail.",
        "hi": "ध्वनि के साथ सामान्य सूचना बैनर। काम के घंटों के लिए उत्तम।",
        "id": "Banner notifikasi standar dengan suara. Tidak mengganggu saat jam kerja.",
        "it": "Banner di notifica standard con suono. Discreto e ideale per le ore di lavoro.",
        "ja": "音声付きの標準バナー通知。仕事中に最適。",
        "kk": "Дыбысы бар стандартты хабарландыру. Жұмыс уақыты үшін ыңғайлы.",
        "ko": "소리가 포함된 기본 배너 알림. 근무 시간에 적합합니다.",
        "ms": "Sepanduk pemberitahuan biasa dengan bunyi. Sesuai untuk waktu kerja.",
        "pa": "ਆਵਾਜ਼ ਵਾਲਾ ਆਮ ਨੋਟੀਫਿਕੇਸ਼ਨ ਬੈਨਰ। ਕੰਮ ਦੇ ਸਮੇਂ ਲਈ ਵਧੀਆ।",
        "ps": "د غږ سره معیاري خبرتیا. د کار د ساعتونو لپاره خورا مناسب.",
        "pt": "Banner de notificação padrão com som. Não intrusivo para o trabalho.",
        "ru": "Обычный баннер со звуком. Ненавязчив и удобен в рабочее время.",
        "sw": "Bango la kawaida la arifa lenye sauti. Zuri wakati wa kazi.",
        "ta": "ஒலியுடன் கூடிய நிலையான அறிவிப்பு பேனர். வேலை நேரத்திற்கு ஏற்றது.",
        "tr": "Sesli standart bildirim başlığı. Rahatsız etmez, mesai saatleri için idealdir.",
        "ur": "آواز کے ساتھ معیاری نوٹیفکیشن بینر۔ کام کے اوقات کے لیے بہترین।",
        "vi": "Biểu ngữ thông báo chuẩn có âm thanh. Không gây phiền khi làm việc.",
        "zh": "带声音的标准横幅通知。不具侵入性，适合工作时间。"
    },
    "presetBalanced": {
        "en": "Balanced", "ar": "متوازن", "az": "Balanslı", "bn": "ভারসাম্যপূর্ণ",
        "de": "Ausgewogen", "es": "Equilibrado", "fa": "متعادل", "fr": "Équilibré",
        "hi": "संतुलित", "id": "Seimbang", "it": "Bilanciato", "ja": "バランス",
        "kk": "Теңгерімді", "ko": "균형", "ms": "Seimbang", "pa": "ਸੰਤੁਲਿਤ",
        "ps": "متوازن", "pt": "Equilibrado", "ru": "Сбалансированный", "sw": "Sawazishwa",
        "ta": "சமச்சீர்", "tr": "Dengeli", "ur": "متوازن", "vi": "Cân bằng", "zh": "平衡"
    },
    "presetBalancedSubtitle": {
        "en": "Fajr Alarm ⏰ + Others Notification 🔔", "ar": "الفجر منبه ⏰ + الباقي إشعار 🔔", "az": "Sübh zəngli saat ⏰ + Digərləri bildiriş 🔔", "bn": "ফজর অ্যালার্ম ⏰ + অন্যান্য নোটিফিকেশন 🔔",
        "de": "Fadschr-Wecker ⏰ + Andere Benachrichtigung 🔔", "es": "Fajr Alarma ⏰ + Otras Notificación 🔔", "fa": "فجر هشدار ⏰ + بقیه اعلان 🔔", "fr": "Fajr Alarme ⏰ + Autres Notification 🔔",
        "hi": "फ़ज्र अलार्म ⏰ + अन्य सूचना 🔔", "id": "Alarm Subuh ⏰ + Lainnya Notifikasi 🔔", "it": "Fajr Sveglia ⏰ + Altre Notifica 🔔", "ja": "ファジュル アラーム ⏰ + 他 通知 🔔",
        "kk": "Таң намазы оятқыш ⏰ + Басқалары хабарландыру 🔔", "ko": "파즈르 알람 ⏰ + 기타 알림 🔔", "ms": "Subuh Penggera ⏰ + Lain-lain Pemberitahuan 🔔", "pa": "ਫ਼ਜਰ ਅਲਾਰਮ ⏰ + ਬਾਕੀ ਨੋਟੀਫਿਕੇਸ਼ਨ 🔔",
        "ps": "فجر الارم ⏰ + نور خبرتیا 🔔", "pt": "Fajr Alarme ⏰ + Outras Notificação 🔔", "ru": "Фаджр будильник ⏰ + Остальные уведомления 🔔", "sw": "Alfajiri Kengele ⏰ + Nyingine Arifa 🔔",
        "ta": "ஃபஜ்ர் அலாரம் ⏰ + மற்றவை அறிவிப்பு 🔔", "tr": "Sabah Alarm ⏰ + Diğerleri Bildirim 🔔", "ur": "فجر الارم ⏰ + دیگر نوٹیفکیشن 🔔", "vi": "Fajr Báo thức ⏰ + Khác Thông báo 🔔", "zh": "晨礼 闹钟 ⏰ + 其他 通知 🔔"
    },
    "presetAllAlarms": {
        "en": "All Alarms", "ar": "جميع الصلوات منبه", "az": "Bütün namazlar zəngli saat", "bn": "সবগুলো অ্যালার্ম",
        "de": "Alle Alarme", "es": "Todas las alarmas", "fa": "تمام هشدارها", "fr": "Toutes les alarmes",
        "hi": "सभी अलार्म", "id": "Semua Alarm", "it": "Tutte le sveglie", "ja": "すべてアラーム",
        "kk": "Барлық оятқыштар", "ko": "모든 알람", "ms": "Semua Penggera", "pa": "ਸਾਰੇ ਅਲਾਰਮ",
        "ps": "ټول الارمونه", "pt": "Todos os alarmes", "ru": "Все будильники", "sw": "Kengele Zote",
        "ta": "அனைத்து அலாரங்கள்", "tr": "Tüm Alarmlar", "ur": "تمام الارم", "vi": "Tất cả báo thức", "zh": "全部闹钟"
    },
    "presetAllAlarmsSubtitle": {
        "en": "Full-Screen Alarm for all prayers", "ar": "منبه ملء الشاشة لجميع الصلوات", "az": "Bütün namazlar üçün tam ekran zəngli saat", "bn": "সবগুলো নামাজের জন্যই ফুল-স্ক্রিন অ্যালার্ম",
        "de": "Vollbild-Alarm für alle Gebete", "es": "Alarma de pantalla completa para todas las oraciones", "fa": "هشدار تمام‌صفحه برای تمام نمازها", "fr": "Alarme plein écran pour toutes les prières",
        "hi": "सभी नमाज़ों के लिए फुल-स्क्रीन अलार्म", "id": "Alarm Layar Penuh untuk semua waktu sholat", "it": "Sveglia a schermo intero per tutte le preghiere", "ja": "すべての礼拝で全画面アラーム",
        "kk": "Барлық намаздар үшін толық экранды оятқыш", "ko": "모든 기도에 전체 화면 알람", "ms": "Penggera Skrin Penuh untuk semua solat", "pa": "ਸਾਰੀਆਂ ਨਮਾਜ਼ਾਂ ਲਈ ਫੁੱਲ-ਸਕ੍ਰੀਨ ਅਲਾਰਮ",
        "ps": "د ټولو لمونځونو لپاره د بشپړ سکرین الارم", "pt": "Alarme em tela cheia para todas as orações", "ru": "Полноэкранный будильник для всех намазов", "sw": "Kengele ya skrini nzima kwa sala zote",
        "ta": "அனைத்து தொழுகைகளுக்கும் முழுத்திரை அலாரம்", "tr": "Tüm namazlar için tam ekran alarm", "ur": "تمام نمازوں کے لیے فل اسکرین الارم", "vi": "Báo thức toàn màn hình cho tất cả giờ cầu nguyện", "zh": "所有礼拜均使用全屏闹钟"
    },
    "presetAllNotifications": {
        "en": "All Notifications", "ar": "جميع الصلوات إشعارات", "az": "Bütün bildirişlər", "bn": "সবগুলো নোটিফিকেশন",
        "de": "Alle Benachrichtigungen", "es": "Todas las notificaciones", "fa": "تمام اعلان‌ها", "fr": "Toutes les notifications",
        "hi": "सभी सूचनाएं", "id": "Semua Notifikasi", "it": "Tutte le notifiche", "ja": "すべて通知",
        "kk": "Барлық хабарландырулар", "ko": "모든 알림", "ms": "Semua Pemberitahuan", "pa": "ਸਾਰੇ ਨੋਟੀਫਿਕੇਸ਼ਨ",
        "ps": "ټولې خبرتیاوې", "pt": "Todas as notificações", "ru": "Все уведомления", "sw": "Arifa Zote",
        "ta": "அனைத்து அறிவிப்புகள்", "tr": "Tüm Bildirimler", "ur": "تمام اطلاعات", "vi": "Tất cả thông báo", "zh": "全部通知"
    },
    "presetAllNotificationsSubtitle": {
        "en": "Gentle banner notifications only", "ar": "إشعارات بانر خفيفة فقط", "az": "Yalnız mülayim bildirişlər", "bn": "শুধুমাত্র হালকা ব্যানার নোটিফিকেশন",
        "de": "Nur sanfte Banner-Benachrichtigungen", "es": "Solo notificaciones suaves", "fa": "فقط اعلان‌های ملایم", "fr": "Notifications discrètes uniquement",
        "hi": "केवल सामान्य सूचनाएं", "id": "Hanya notifikasi banner lembut", "it": "Solo notifiche discrete", "ja": "穏やかなバナー通知のみ",
        "kk": "Тек жұмсақ хабарландырулар", "ko": "부드러운 배너 알림만", "ms": "Hanya pemberitahuan sepanduk lembut", "pa": "ਸਿਰਫ਼ ਹਲਕੇ ਨੋਟੀਫਿਕੇਸ਼ਨ",
        "ps": "یوازې نرمې خبرتیاوې", "pt": "Apenas notificações suaves", "ru": "Только мягкие уведомления", "sw": "Arifa za upole pekee",
        "ta": "மென்மையான அறிவிப்புகள் மட்டுமே", "tr": "Yalnızca hafif bildirimler", "ur": "صرف ہلکی نوٹیفیکیشن", "vi": "Chỉ thông báo nhẹ nhàng", "zh": "仅温和横幅通知"
    },
    "saveAndReturn": {
        "en": "Save & Return", "ar": "حفظ والرجوع", "az": "Saxla və qayıt", "bn": "সংরক্ষণ করুন ও ফিরে যান",
        "de": "Speichern & Zurück", "es": "Guardar y volver", "fa": "ذخیره و بازگشت", "fr": "Enregistrer et revenir",
        "hi": "सहेजें और वापस जाएं", "id": "Simpan & Kembali", "it": "Salva e torna indietro", "ja": "保存して戻る",
        "kk": "Сақтау және оралу", "ko": "저장 및 돌아가기", "ms": "Simpan & Kembali", "pa": "ਸੰਭਾਲੋ ਅਤੇ ਵਾਪਸ ਜਾਓ",
        "ps": "ساتل او بیرته ستنېدل", "pt": "Salvar e voltar", "ru": "Сохранить и вернуться", "sw": "Hifadhi na Urudi",
        "ta": "சேமித்து திரும்புக", "tr": "Kaydet ve Geri Dön", "ur": "محفوظ کریں اور واپس جائیں", "vi": "Lưu & Quay lại", "zh": "保存并返回"
    },
    "saveAndGetStarted": {
        "en": "Save & Get Started", "ar": "حفظ والبدء", "az": "Saxla və başla", "bn": "সংরক্ষণ করুন ও শুরু করুন",
        "de": "Speichern & Loslegen", "es": "Guardar y comenzar", "fa": "ذخیره و شروع", "fr": "Enregistrer et commencer",
        "hi": "सहेजें और शुरू करें", "id": "Simpan & Mulai", "it": "Salva e inizia", "ja": "保存して開始",
        "kk": "Сақтау және бастау", "ko": "저장 및 시작하기", "ms": "Simpan & Mula", "pa": "ਸੰਭਾਲੋ ਅਤੇ ਸ਼ੁਰੂ ਕਰੋ",
        "ps": "ساتل او پیل کول", "pt": "Salvar e começar", "ru": "Сохранить и начать", "sw": "Hifadhi na Anza",
        "ta": "சேமித்து தொடங்குக", "tr": "Kaydet ve Başla", "ur": "محفوظ کریں اور شروع کریں", "vi": "Lưu & Bắt đầu", "zh": "保存并开始"
    },
    "granted": {
        "en": "Granted", "ar": "تم المنح", "az": "İcazə verildi", "bn": "অনুমতি দেওয়া হয়েছে",
        "de": "Gewährt", "es": "Concedido", "fa": "اعطا شد", "fr": "Accordé",
        "hi": "अनुमति दी गई", "id": "Diberikan", "it": "Concesso", "ja": "許可済み",
        "kk": "Рұқсат берілді", "ko": "허용됨", "ms": "Diberikan", "pa": "ਆਗਿਆ ਦਿੱਤੀ ਗਈ",
        "ps": "اجازه ورکړل شوه", "pt": "Concedido", "ru": "Предоставлено", "sw": "Imeruhusiwa",
        "ta": "வழங்கப்பட்டது", "tr": "Verildi", "ur": "اجازت مل گئی", "vi": "Đã cấp", "zh": "已授予"
    },
    "requiredPermissions": {
        "en": "Required Permissions", "ar": "الأذونات المطلوبة", "az": "Tələb olunan icazələr", "bn": "প্রয়োজনীয় অনুমতিসমূহ",
        "de": "Erforderliche Berechtigungen", "es": "Permisos requeridos", "fa": "مجوزهای مورد نیاز", "fr": "Autorisations requises",
        "hi": "आवश्यक अनुमतियाँ", "id": "Izin yang Diperlukan", "it": "Autorizzazioni richieste", "ja": "必要な権限",
        "kk": "Қажетті рұқсаттар", "ko": "필요한 권한", "ms": "Kebenaran Diperlukan", "pa": "ਲੋੜੀਂਦੀਆਂ ਇਜਾਜ਼ਤਾਂ",
        "ps": "اړینې اجازې", "pt": "Permissões necessárias", "ru": "Необходимые разрешения", "sw": "Ruhusa Zinazohitajika",
        "ta": "தேவையான அனுமதிகள்", "tr": "Gerekli İzinler", "ur": "مطلوبہ اجازتیں", "vi": "Quyền được yêu cầu", "zh": "所需权限"
    },
    "skip": {
        "en": "Skip", "ar": "تخطي", "az": "Keç", "bn": "স্কিপ",
        "de": "Überspringen", "es": "Saltar", "fa": "رد کردن", "fr": "Passer",
        "hi": "छोड़ें", "id": "Lewati", "it": "Salta", "ja": "スキップ",
        "kk": "Өткізіп жіберу", "ko": "건너뛰기", "ms": "Langkau", "pa": "ਛੱਡੋ",
        "ps": "پریږدئ", "pt": "Pular", "ru": "Пропустить", "sw": "Ruka",
        "ta": "தவிர்", "tr": "Geç", "ur": "چھوڑیں", "vi": "Bỏ qua", "zh": "跳过"
    },
    "skipForNow": {
        "en": "Skip for now", "ar": "تخطي الآن", "az": "Hələlik keç", "bn": "আপাতত স্কিপ করুন",
        "de": "Vorerst überspringen", "es": "Omitir por ahora", "fa": "فعلاً رد شود", "fr": "Passer pour l'instant",
        "hi": "अभी के लिए छोड़ें", "id": "Lewati sekarang", "it": "Salta per ora", "ja": "今はスキップ",
        "kk": "Әзірге өткізіп жіберу", "ko": "지금은 건너뛰기", "ms": "Langkau buat masa ini", "pa": "ਹੁਣ ਲਈ ਛੱਡੋ",
        "ps": "اوس لپاره پریږدئ", "pt": "Pular por enquanto", "ru": "Пропустить сейчас", "sw": "Ruka kwa sasa",
        "ta": "இப்போதைக்கு தவிர்", "tr": "Şimdilik geç", "ur": "ابھی کے لیے چھوڑیں", "vi": "Bỏ qua bây giờ", "zh": "暂且跳过"
    },
    "exactAlarmPermission": {
        "en": "Exact Alarms", "ar": "التنبيهات الدقيقة", "az": "Dəqiq siqnallar", "bn": "সঠিক অ্যালার্ম",
        "de": "Genaue Alarme", "es": "Alarmas exactas", "fa": "هشدارهای دقیق", "fr": "Alarmes exactes",
        "hi": "सटीक अलार्म", "id": "Alarm Tepat", "it": "Allarmi esatti", "ja": "正確なアラーム",
        "kk": "Дәл оятқыштар", "ko": "정확한 알람", "ms": "Penggera Tepat", "pa": "ਸਹੀ ਅਲਾਰਮ",
        "ps": "دقیق الارمونه", "pt": "Alarmes exatos", "ru": "Точные будильники", "sw": "Kengele Sahihi",
        "ta": "துல்லியமான அலாரங்கள்", "tr": "Tam Zamanlı Alarmlar", "ur": "درست الارم", "vi": "Báo thức chính xác", "zh": "精准闹钟"
    },
    "exactAlarmPermissionDesc": {
        "en": "Triggers notifications precisely at prayer times",
        "ar": "إطلاق التنبيهات في أوقات الصلاة بدقة",
        "az": "Namaz vaxtlarında dəqiq bildirişləri işə salır",
        "bn": "নামাজের নির্ধারিত সময়ে নিখুঁতভাবে অ্যালার্ম চালু করে",
        "de": "Löst Benachrichtigungen genau zu den Gebetszeiten aus",
        "es": "Activa notificaciones precisamente a las horas de oración",
        "fa": "اعلان‌ها را دقیقاً در زمان‌های نماز فعال می‌کند",
        "fr": "Déclenche les notifications précisément aux heures de prière",
        "hi": "नमाज़ के समय पर सटीक सूचनाएं चालू करता है",
        "id": "Memicu notifikasi tepat pada waktu shalat",
        "it": "Attiva le notifiche esattamente agli orari di preghiera",
        "ja": "礼拝の時間に正確に通知を作動させます",
        "kk": "Намаз уақытында хабарландыруларды дәл жібереді",
        "ko": "기도 시간에 정확히 알림을 울립니다",
        "ms": "Mencetuskan pemberitahuan tepat pada waktu solat",
        "pa": "ਨਮਾਜ਼ ਦੇ ਸਮੇਂ ਸਹੀ ਸੂਚਨਾਵਾਂ ਭੇਜਦਾ ਹੈ",
        "ps": "د لمانځه په وخت کې دقیق خبرتیاوې پیلوي",
        "pt": "Dispara notificações exatamente nos horários de oração",
        "ru": "Запускает уведомления точно во время молитвы",
        "sw": "Hutoa arifa kwa usahihi wakati wa sala",
        "ta": "தொழுகை நேரங்களில் துல்லியமாக அறிவிப்புகளைத் தூண்டுகிறது",
        "tr": "Namaz vakitlerinde tam vaktinde bildirim gönderir",
        "ur": "نماز کے اوقات میں عین وقت پر اطلاعات جاری کرتا ہے",
        "vi": "Kích hoạt thông báo chính xác vào giờ cầu nguyện",
        "zh": "在礼拜时间准时触发通知"
    },
    "appDefaultTone": {
        "en": "App Default Tone", "ar": "نغمة التطبيق الافتراضية", "az": "Tətbiqin standart səsi", "bn": "অ্যাপ ডিফল্ট টোন",
        "de": "Standard-App-Ton", "es": "Tono predeterminado de la app", "fa": "صدای پیش‌فرض برنامه", "fr": "Son par défaut de l'application",
        "hi": "ऐप डिफ़ॉल्ट टोन", "id": "Nada Default Aplikasi", "it": "Tono predefinito dell'app", "ja": "アプリのデフォルト音",
        "kk": "Қолданбаның әдепкі дыбысы", "ko": "앱 기본음", "ms": "Nada Lalai Aplikasi", "pa": "ਐਪ ਡਿਫੌਲਟ ਟੋਨ",
        "ps": "د اپلیکیشن ډیفالټ غږ", "pt": "Tom padrão do app", "ru": "Стандартный звук приложения", "sw": "Mlio Chaguomsingi wa Programu",
        "ta": "செயலியின் இயல்புநிலை ஒலி", "tr": "Uygulama Varsayılan Sesi", "ur": "ایپ کی پہلے سے طے شدہ آواز", "vi": "Âm mặc định ứng dụng", "zh": "应用默认铃声"
    },
    "systemAlarmTone": {
        "en": "System Alarm Tone", "ar": "نغمة منبه النظام", "az": "Sistem siqnal səsi", "bn": "সিস্টেম অ্যালার্ম টোন",
        "de": "Systemalarm-Ton", "es": "Tono de alarma del sistema", "fa": "صدای زنگ سیستم", "fr": "Sonnerie d'alarme système",
        "hi": "सिस्टम अलार्म टोन", "id": "Nada Alarm Sistem", "it": "Tono sveglia di sistema", "ja": "システムアラーム音",
        "kk": "Жүйелік оятқыш дыбысы", "ko": "시스템 알람음", "ms": "Nada Penggera Sistem", "pa": "ਸਿਸਟਮ ਅਲਾਰਮ ਟੋਨ",
        "ps": "د سیسټم د الارم غږ", "pt": "Tom de alarme do sistema", "ru": "Системный сигнал будильника", "sw": "Mlio wa Kengele ya Mfumo",
        "ta": "கணினி அலாரம் ஒலி", "tr": "Sistem Alarm Sesi", "ur": "سسٹم الارم کی آواز", "vi": "Chuông báo thức hệ thống", "zh": "系统闹钟铃声"
    }
}

for lang in languages:
    file_path = f"lib/l10n/app_{lang}.arb"
    if os.path.exists(file_path):
        with open(file_path, 'r', encoding='utf-8') as f:
            try:
                data = json.load(f)
            except Exception as e:
                print(f"Error loading {file_path}: {e}")
                continue

        updated = False
        for key, lang_map in translations.items():
            val = lang_map.get(lang, lang_map.get("en"))
            if key not in data or data[key] != val:
                data[key] = val
                updated = True

        if updated:
            with open(file_path, 'w', encoding='utf-8') as f:
                json.dump(data, f, ensure_ascii=False, indent=2)
                f.write('\n')
            print(f"Updated {file_path}")
        else:
            print(f"No new keys needed for {file_path}")
    else:
        print(f"File {file_path} does not exist.")

print("All language ARB files updated successfully.")