Map<String, String> languageToCodeMap = {
  'bulgarian': 'bg',
  'persian': 'fa',
  'macedonian': 'mk',
  'kashmiri': 'ks',
  'bosnian': 'bs',
  'amharic': 'am',
  'bengali': 'bn',
  'english': 'en',
  'spanish': 'es',
  'divehi': 'dv',
  'uighur': 'ug',
  'somali': 'so',
  'italian': 'it',
  'serbian': 'sr',
  'kazakh': 'kk',
  'amazigh': 'zgh',
  'marathi': 'mr',
  'telugu': 'te',
  'ukrainian': 'uk',
  'hindi': 'hi',
  'chinese': 'zh',
  'maltese': 'mt',
  'kurdish': 'ku',
  'gujarati': 'gu',
  'sindhi': 'sd',
  'asante': 'ak',
  'yoruba': 'yo',
  'lithuanian': 'lt',
  'portuguese': 'pt',
  'german': 'de',
  'bambara': 'bm',
  'malayalam': 'ml',
  'french': 'fr',
  'nepali': 'ne',
  'ganda': 'lg',
  'assamese': 'as',
  'chechen': 'ce',
  'polish': 'pl',
  'tajik': 'tg',
  'kinyarwanda': 'rw',
  'urdu': 'ur',
  'central_khmer': 'km', // key is now 'central_khmer'
  'romanian': 'ro',
  'swahili': 'sw',
  'hausa': 'ha',
  'japanese': 'ja',
  'vietnamese': 'vi',
  'tatar': 'tt',
  'hebrew': 'he',
  'turkish': 'tr',
  'yau': 'yao', // key is now 'yau'
  'russian': 'ru',
  'czech': 'cs',
  'thai': 'th',
  'azeri': 'az', // key is now 'azeri'
  'finnish': 'fi',
  'kannada': 'kn',
  'tagalog': 'tl',
  'norwegian': 'no',
  'korean': 'ko',
  'uzbek': 'uz',
  'oromo': 'om',
  'pashto': 'ps',
  'sinhala': 'si',
  'indonesian': 'id',
  'dutch': 'nl',
  'albanian': 'sq',
  'malay': 'ms',
  'tamil': 'ta',
  'swedish': 'sv',
  'maranao': 'mrn',
  'arabic': 'ar',
};

Map<String, String> languageNativeNames = {
  'bulgarian': 'Български',
  'persian': 'فارسی',
  'macedonian': 'Македонски',
  'kashmiri': 'کٲشُر',
  'bosnian': 'Bosanski',
  'amharic': 'አማርኛ',
  'bengali': 'বাংলা',
  'english': 'English',
  'spanish': 'Español',
  'divehi': 'ދިވެހި',
  'uighur': 'ئۇيغۇرچە',
  'somali': 'Soomaali',
  'italian': 'Italiano',
  'serbian': 'Српски',
  'kazakh': 'Қазақша',
  'amazigh': 'ⵜⴰⵎⴰⵣⵉⵖⵜ',
  'marathi': 'मराठी',
  'telugu': 'తెలుగు',
  'ukrainian': 'Українська',
  'hindi': 'हिन्दी',
  'chinese': '中文',
  'maltese': 'Malti',
  'kurdish': 'کوردی',
  'gujarati': 'ગુજરાતી',
  'sindhi': 'سنڌي',
  'asante': 'Twi',
  'yoruba': 'Yorùbá',
  'lithuanian': 'Lietuvių',
  'portuguese': 'Português',
  'german': 'Deutsch',
  'bambara': 'Bamanankan',
  'malayalam': 'മലയാളം',
  'french': 'Français',
  'nepali': 'नेपाली',
  'ganda': 'Luganda',
  'assamese': 'অসমীয়া',
  'chechen': 'Нохчийн',
  'polish': 'Polski',
  'tajik': 'Тоҷикӣ',
  'kinyarwanda': 'Kinyarwanda',
  'urdu': 'اُردُو',
  'central_khmer': 'ខ្មែរ', // key is now 'central_khmer'
  'romanian': 'Română',
  'swahili': 'Kiswahili',
  'hausa': 'Hausa',
  'japanese': '日本語',
  'vietnamese': 'Tiếng Việt',
  'tatar': 'Татарча',
  'hebrew': 'עברית',
  'turkish': 'Türkçe',
  'yao': 'Chiyao', // key is now 'yao'
  'russian': 'Русский',
  'czech': 'Čeština',
  'thai': 'ไทย',
  'azeri': 'Azərbaycanca', // key is now 'azeri'
  'finnish': 'Suomi',
  'kannada': 'ಕನ್ನಡ',
  'tagalog': 'Tagalog',
  'norwegian': 'Norsk',
  'korean': '한국어',
  'uzbek': 'Oʻzbekcha',
  'oromo': 'Afaan Oromoo',
  'pashto': 'پښتو',
  'sinhala': 'සිංහල',
  'indonesian': 'Bahasa Indonesia',
  'dutch': 'Nederlands',
  'albanian': 'Shqip',
  'malay': 'Bahasa Melayu',
  'tamil': 'தமிழ்',
  'swedish': 'Svenska',
  'maranao': 'Maranao',
  'arabic': 'العربية',
};
