import "package:al_quran_v3/main.dart";
import "package:al_quran_v3/src/resources/translation/language_cubit.dart";
import "package:flutter/material.dart";
import "package:flutter_bloc/flutter_bloc.dart";

String getSurahName(BuildContext? context, int index) {
  context ??= navigatorKey.currentContext!;
  Locale locale = context.read<LanguageCubit>().state.locale;
  return List<String>.from(
    surahNameLocalization[locale.languageCode] ?? surahNameLocalization["en"],
  )[index - 1];
}

String getSurahNameArabic(int index) {
  return List<String>.from(surahNameLocalization["ar"])[index - 1];
}

String getSurahMeaning(BuildContext? context, int index) {
  context ??= navigatorKey.currentContext!;
  Locale locale = context.read<LanguageCubit>().state.locale;
  return meaningOfSurahEnglish[index - 1];
}

List<String> meaningOfSurahEnglish = [
  "The Opening",
  "The Cow",
  "The Family of Imran",
  "The Women",
  "The Table Spread ",
  "The Cattle",
  "The Heights",
  "The Spoils of War",
  "The Repentance",
  "Jonah ",
  "Hud ",
  "Joseph ",
  "The Thunder",
  "Abraham ",
  "The Rocky Tract ",
  "The Bee",
  "The Night Journey",
  "The Cave",
  "Mary ",
  "Ta-Ha ",
  "The Prophets",
  "The Pilgrimage",
  "The Believers",
  "The Light",
  "The Criterion ",
  "The Poets",
  "The Ant",
  "The Stories",
  "The Spider",
  "The Romans",
  "Luqman ",
  "The Prostration",
  "The Combined Forces ",
  "Sheba ",
  "The Originator ",
  "Ya Sin ",
  "Those Ranged in Ranks",
  "Sad ",
  "The Groups ",
  "The Forgiver ",
  "Explained in Detail",
  "The Consultation",
  "The Ornaments of Gold ",
  "The Smoke",
  "The Crouching ",
  "The Wind-Curved Sandhills ",
  "Muhammad ",
  "The Victory ",
  "The Inner Apartments ",
  "Qaf ",
  "The Winnowing Winds ",
  "The Mount",
  "The Star",
  "The Moon",
  "The Most Gracious ",
  "The Inevitable Event ",
  "The Iron",
  "The Pleading Woman ",
  "The Gathering ",
  "She that is to be Examined ",
  "The Ranks ",
  "The Congregation ",
  "The Hypocrites",
  "The Mutual Loss and Gain ",
  "The Divorce",
  "The Prohibition",
  "The Dominion ",
  "The Pen",
  "The Reality ",
  "The Ways of Ascent ",
  "Noah ",
  "The Jinn ",
  "The Enshrouded One ",
  "The Cloaked One ",
  "The Resurrection",
  "Man ",
  "Those Sent Forth ",
  "The Great News ",
  "Those Who Pull Out ",
  "He Frowned",
  "The Overthrowing ",
  "The Cleaving Asunder ",
  "The Defrauders ",
  "The Splitting Asunder ",
  "The Constellations ",
  "The Nightcomer ",
  "The Most High",
  "The Overwhelming Event ",
  "The Dawn",
  "The City",
  "The Sun",
  "The Night",
  "The Morning Hours ",
  "The Opening Forth ",
  "The Fig",
  "The Clot ",
  "The Night of Decree ",
  "The Clear Evidence ",
  "The Earthquake",
  "The Chargers ",
  "The Striking Hour ",
  "The Piling Up ",
  "The Time ",
  "The Slanderer ",
  "The Elephant",
  "Quraysh ",
  "The Small Kindnesses ",
  "The Abundance",
  "The Disbelievers",
  "The Divine Support ",
  "The Palm Fiber ",
  "The Sincerity ",
  "The Daybreak ",
  "Mankind",
];
