// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyAjn3FD9B4ePKvLWC88_y7-jcoUQF9outE',
//     appId: '1:562324718404:web:5ec03a3376dd9b7f69cd11',
//     messagingSenderId: '562324718404',
//     projectId: 'alquranwithaudio',
//     authDomain: 'alquranwithaudio.firebaseapp.com',
//     storageBucket: 'alquranwithaudio.appspot.com',
//     measurementId: 'G-ZVZ8RCNS5N',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyAvNykaA8z6YaQ3wVS1kOLpnOMZI91d8vk',
//     appId: '1:562324718404:android:edab7cc24328618369cd11',
//     messagingSenderId: '562324718404',
//     projectId: 'alquranwithaudio',
//     storageBucket: 'alquranwithaudio.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyA5QqTpPsslnVbQQv0blQJWWNOnh7RaCTM',
//     appId: '1:562324718404:ios:81d2303f351ff2d269cd11',
//     messagingSenderId: '562324718404',
//     projectId: 'alquranwithaudio',
//     storageBucket: 'alquranwithaudio.appspot.com',
//     iosBundleId: 'com.ismail-hosen-james.al-bayan-quran',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyA5QqTpPsslnVbQQv0blQJWWNOnh7RaCTM',
//     appId: '1:562324718404:ios:81d2303f351ff2d269cd11',
//     messagingSenderId: '562324718404',
//     projectId: 'alquranwithaudio',
//     storageBucket: 'alquranwithaudio.appspot.com',
//     iosBundleId: 'com.ismail-hosen-james.al-bayan-quran',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyAjn3FD9B4ePKvLWC88_y7-jcoUQF9outE',
//     appId: '1:562324718404:web:5ec03a3376dd9b7f69cd11',
//     messagingSenderId: '562324718404',
//     projectId: 'alquranwithaudio',
//     authDomain: 'alquranwithaudio.firebaseapp.com',
//     storageBucket: 'alquranwithaudio.appspot.com',
//     measurementId: 'G-ZVZ8RCNS5N',
//   );
// }
