// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOH4wEowbaI6JB0Uc4AR4wBPwgBHMWFs4',
    appId: '1:562324718404:web:d5bab63f6b42e07b69cd11',
    messagingSenderId: '562324718404',
    projectId: 'alquranwithaudio',
    authDomain: 'alquranwithaudio.firebaseapp.com',
    databaseURL: 'https://alquranwithaudio-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'alquranwithaudio.appspot.com',
    measurementId: 'G-2Y5HBXNV26',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvNykaA8z6YaQ3wVS1kOLpnOMZI91d8vk',
    appId: '1:562324718404:android:cc17455127c7825269cd11',
    messagingSenderId: '562324718404',
    projectId: 'alquranwithaudio',
    databaseURL: 'https://alquranwithaudio-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'alquranwithaudio.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5QqTpPsslnVbQQv0blQJWWNOnh7RaCTM',
    appId: '1:562324718404:ios:d2707ed437a712c269cd11',
    messagingSenderId: '562324718404',
    projectId: 'alquranwithaudio',
    databaseURL: 'https://alquranwithaudio-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'alquranwithaudio.appspot.com',
    androidClientId: '562324718404-airjj0ovl6jp5nk3g823qmslo0mm71n7.apps.googleusercontent.com',
    iosClientId: '562324718404-4s2sokj9dls2qtc2t5ph95vrdgic6obr.apps.googleusercontent.com',
    iosBundleId: 'com.ismail-hosen-james.al-bayan-quran',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5QqTpPsslnVbQQv0blQJWWNOnh7RaCTM',
    appId: '1:562324718404:ios:d2707ed437a712c269cd11',
    messagingSenderId: '562324718404',
    projectId: 'alquranwithaudio',
    databaseURL: 'https://alquranwithaudio-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'alquranwithaudio.appspot.com',
    androidClientId: '562324718404-airjj0ovl6jp5nk3g823qmslo0mm71n7.apps.googleusercontent.com',
    iosClientId: '562324718404-4s2sokj9dls2qtc2t5ph95vrdgic6obr.apps.googleusercontent.com',
    iosBundleId: 'com.ismail-hosen-james.al-bayan-quran',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOH4wEowbaI6JB0Uc4AR4wBPwgBHMWFs4',
    appId: '1:562324718404:web:5f4bb2a3484ed1dc69cd11',
    messagingSenderId: '562324718404',
    projectId: 'alquranwithaudio',
    authDomain: 'alquranwithaudio.firebaseapp.com',
    databaseURL: 'https://alquranwithaudio-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'alquranwithaudio.appspot.com',
    measurementId: 'G-R9M3P7MFJQ',
  );

}